export const PERMISSIONS = {
    VIEW_DASHBOARD: "VIEW_DASHBOARD",
    VIEW_PROJECTS: "VIEW_PROJECTS",
    VIEW_ISSUES: "VIEW_ISSUES",
    CREATE_ISSUE: "CREATE_ISSUE",
    EDIT_ISSUE: "EDIT_ISSUE",
    DELETE_ISSUE: "DELETE_ISSUE",
    ASSIGN_ISSUE: "ASSIGN_ISSUE",
    CHANGE_STATUS: "CHANGE_STATUS",
    MANAGE_USERS: "MANAGE_USERS",
    MANAGE_ROLES: "MANAGE_ROLES",
    VIEW_ANALYTICS: "VIEW_ANALYTICS",
    VIEW_AI_RESOLUTION: "VIEW_AI_RESOLUTION",
    VIEW_AI_DEVELOPER_RECOMMENDATION: "VIEW_AI_DEVELOPER_RECOMMENDATION",
    ADD_COMMENT: "ADD_COMMENT",
    UPLOAD_ATTACHMENT: "UPLOAD_ATTACHMENT",
    DELETE_ATTACHMENT: "DELETE_ATTACHMENT",
    MANAGE_SPRINTS: "MANAGE_SPRINTS",
  };
  
  const ALL = Object.values(PERMISSIONS);
  
  export const ROLE_PERMISSIONS = {
    admin: ALL,
    manager: [
      PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_PROJECTS, PERMISSIONS.VIEW_ISSUES,
      PERMISSIONS.CREATE_ISSUE, PERMISSIONS.EDIT_ISSUE, PERMISSIONS.ASSIGN_ISSUE,
      PERMISSIONS.CHANGE_STATUS, PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.VIEW_AI_RESOLUTION,
      PERMISSIONS.VIEW_AI_DEVELOPER_RECOMMENDATION, PERMISSIONS.ADD_COMMENT,
      PERMISSIONS.UPLOAD_ATTACHMENT, PERMISSIONS.MANAGE_SPRINTS,
    ],
    developer: [
      PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_PROJECTS, PERMISSIONS.VIEW_ISSUES,
      PERMISSIONS.EDIT_ISSUE, PERMISSIONS.CHANGE_STATUS, PERMISSIONS.VIEW_ANALYTICS,
      PERMISSIONS.VIEW_AI_RESOLUTION, PERMISSIONS.VIEW_AI_DEVELOPER_RECOMMENDATION,
      PERMISSIONS.ADD_COMMENT, PERMISSIONS.UPLOAD_ATTACHMENT,
    ],
    qa: [
      PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_PROJECTS, PERMISSIONS.VIEW_ISSUES,
      PERMISSIONS.CREATE_ISSUE, PERMISSIONS.EDIT_ISSUE, PERMISSIONS.CHANGE_STATUS,
      PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.VIEW_AI_RESOLUTION,
      PERMISSIONS.VIEW_AI_DEVELOPER_RECOMMENDATION, PERMISSIONS.ADD_COMMENT,
      PERMISSIONS.UPLOAD_ATTACHMENT,
    ],
    reporter: [
      PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_PROJECTS, PERMISSIONS.VIEW_ISSUES,
      PERMISSIONS.CREATE_ISSUE, PERMISSIONS.ADD_COMMENT, PERMISSIONS.UPLOAD_ATTACHMENT,
      PERMISSIONS.VIEW_AI_RESOLUTION, PERMISSIONS.VIEW_ANALYTICS,
      PERMISSIONS.VIEW_AI_DEVELOPER_RECOMMENDATION,
    ],
  };
  
  export function hasPermission(role, permission) {
    return (ROLE_PERMISSIONS[role] || []).includes(permission);
  }
  
  export function hasRole(role, ...allowedRoles) {
    return allowedRoles.includes(role);
  }